### ISSUE TITLE
RTX 2070 / 2080 Crash/loading 

### ISSUE THREAD

**Issue by Hugbee1** [tsunamayo/Skywanderers#1152]
### Short Description of the issue:
crash to desktop or stuck on loading screen but i can press esc to see my mouse 
...

### Steps to reproduce the issue:

...just load game 

### Environment
- Skywanderers version: 19w22c
- Graphics Card: rtx 2070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243191/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, sorry to hear that. Is this a crash to desktop or an infinite loading screen? Also are you from the new wave or did you started from an existing save (if it is the case I will need your save folder).
Thanks!

**Comment by Hugbee1** [comment]
yes form the new wave   and i haven't got that far yet to have a save

**Comment by Hugbee1** [comment]
i can use mouse wheel in loading screen just got a clicking sound

**Comment by ColonelCabbage** [comment]
Hi, I am also on an RTX 2070 and am having the same issue

**Comment by tsunamayo** [comment]
Okay I just pushed a new build, 19w22d. It fixes the fresh start issue. Could you please delete your save_data folder and recreate a new player?
C:\Users\Francois\AppData\LocalLow\TsunamayoCorp\Skywanderers\Save_Data
Tell me how it worked. 
Cheers!

**Comment by thecold1** [comment]
### **Short Description of the issue:**
Same error.

When I start to load a fresh game (new installation and even if I delete SaveData) i'm stuck on the loading screen. the "loading" stops pulsating, I hear a crackling/snare sound and nothing happens.

But I can press number keys and hear a sound. I can press Tab and see my cursor and hover over a invisible menu and see my cursoer change to a hand. I can also press ESC and click where the "quit game" button should be and the game closes without a crash. 

Sometimes the game crashes while I click around after having pressed Tab.

### **Steps to reproduce the issue:**
Start new game


### **Environment**
Skywanderers version: 19w22d
Graphics Card: RTX 2080

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243387/output_log.txt)

**Comment by tsunamayo** [comment]
Okay just to confirm, is your driver and Directx up to date?

**Comment by thecold1** [comment]
Nvidia GeForce Game Ready Driver up2date 430.86 from 05/27/2019

DirectXVersion 12:
[DxDiag.txt](https://github.com/tsunamayo/Skywanderers/files/3243403/DxDiag.txt)

**Comment by tsunamayo** [comment]
I just pushed a (tentative) fix build 19w22e for RTX. My guess is that it is linked to the 8gb memory of both the 2070 and 2080, but as I dont have a RTX I cant confirm (still coding on an old GTX960 ^^) Keep me posted on the result! Thanks

**Comment by Tommyg930** [comment]
No joy. The game (19w22f) still gets stuck in loading screen. I do hear a snap sound like I've opened the parts picker.
it crashes to desktop after a brief flash of the crash handler showing on screen.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243446/output_log.txt)

P.S: not part of the new wave, but I reinstalled my computer when I upgraded from a GTX 970 to an RTX 2080, so I'm starting Sky wanderers fresh.

**Comment by tsunamayo** [comment]
Are you a new backer (want to know if your save folder is empty or not)? I pushed a new version, the g, with an even lower buffer threshold. What I am not sure is why I only seems to see 3gb from within Unity. Sorry as I dont have a RTX it will be a bit painful to fix with a lot of back and forth, but we will figure it out! Thanks

**Comment by Tommyg930** [comment]
Hey if in the end it will fix the issue and allow me to play it, I don't mind going back and forth. I posted the crash log you asked for in the new build topic for 19w22g

**Comment by Cobra-Mode** [comment]
I'm also having the same problem on the 2080. I've included the log.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3243837/output_log.txt)

**Comment by tsunamayo** [comment]
@Cobra-Mode @Tommyg930 could you make sure your driver are up to date? In the log file it seems that they might be a bit outdated. Keep me posted if that makes things better (cant be worse ....) Thanks

**Comment by Cobra-Mode** [comment]
I've just updated the drivers. I hadn't update for a while, so it certainly could have been the cause, but sadly  I have the same problem still.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3245032/output_log.txt)

**Comment by Hugbee1** [comment]
still not working all drivers up to date

**Comment by Tommyg930** [comment]
@tsunamayo Those drivers are the latest from my card's manufacturer.  Downloaded the latest from Nvida itself. no change.

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3246649/output_log.txt)

**Comment by Hugbee1** [comment]
If it come to it as the game is unplayable for me  yes I understand its a early alpha and bugs are expected as with every alpha out there but these alpha have been playable to some degree this isn't  what's the refund process?

**Comment by tsunamayo** [comment]
Hi guys, so the next step for this issue is for me to visit a friend next week-end and debug on-site. So best scenario I can find a work-around and make the game work on RTX next week-end, but there is also the possibility that it require a fix from Unity / Nvidia team, which could takes longer. 
I updated the engine to two different versions to no avail. I am 100% confident this will be eventually resolved in time. If you can't wait and would like to talk refund please send me a mail. Thanks!

**Comment by Hugbee1** [comment]
That's cool just wanted to put the question out there  happy to wait

**Comment by tsunamayo** [comment]
@Hugbee1 @ColonelCabbage @thecold1 @Tommyg930 
So you can check 19w23d, bug should be fixed! Tell me if it works.
Thanks for your patience! Cheers

**Comment by thecold1** [comment]
Can confirm, bug is solved for me.

Geforce RTX 2080.

Good work!

**Comment by ColonelCabbage** [comment]
Fixed here as well. RTX 2070


________________________________

**Comment by tsunamayo** [comment]
Fantatistique ;) Thanks for backing and testing, cheers ^^
