### ISSUE TITLE
[BUG] Too much velocity rating will break your ship

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1553]
### Short Description of the issue:
In your ship core, you can view a stat that goes by Velocity Rating. If you get it too high (>450%), your ship will be unable to be controlled, and speed in the hud will just display random numbers.

### Steps to reproduce the issue:
1. Make a ship with >450% Velocity Rating (Or just use this one 
[VelocityRatingTesting.zip](https://github.com/tsunamayo/Skywanderers/files/4049501/VelocityRatingTesting.zip))
2. Take control of it, and try to fly with it.

### Environment
- Skywanderers version: 20w02b
- Graphics Card: AMD RX 580

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4049502/output_log.txt)

**Comment by tsunamayo** [comment]
Okay it is now fixed, it was my PID doing jittering with large thrust. I also updated the balance spreadsheet with the forward and agility rating computation: rating = LN(1 + ThrustToWeight).
This is very basic for now, will refine this formula if necessary.
Thanks!

**Comment by AfterRebelion** [comment]
I can still reproduce the issue with a Velocity Rating of more than 650%
[VelocityRatingTesting2.zip](https://github.com/tsunamayo/Skywanderers/files/4050883/VelocityRatingTesting2.zip)
This one was made with 666% rating so it's more cursed.
