### ISSUE TITLE
[Bug] Freeform Blocks and Custom colors.

### ISSUE THREAD

**Issue by Name11ess** [tsunamayo/Skywanderers#559]
Hello!

It seems like the custom colors don't work on the Freeform blocks. It will always be the default color of the custom color that'll be shown on the blocks.
Here, the block on the top is the modified custom color on the standard block, and on a FFB on the bottom. The colour should be blue in both case.

![image](https://user-images.githubusercontent.com/33256107/36758817-c6081e0c-1c15-11e8-86c3-f09ba842307e.png)

**Comment by tsunamayo** [comment]
Okay issue is now fixed! Thanks for being so active reporting bugs ;-) Merci Cheers

**Comment by Name11ess** [comment]
Thanks for being so active fixing bugs! 😄

**Comment by chunkblaster** [comment]
I'm currently on the experimental branch & am still having this issue, the custom colors are showing up as their default colors..

I'm not exactly sure what additional info to provide so let me know what else I can provide you with

**Comment by chunkblaster** [comment]
Ok I have an Addendum, it appears to be a specific creation that is having the issue, Is there any known way to remedy this? it's a wrather intricate build that I don't want to recreate unless absolutely necessary...

**Comment by chunkblaster** [comment]
[Titan Mk3 Heavy Assault Mech.zip](https://github.com/tsunamayo/Skywanderers/files/1813987/Titan.Mk3.Heavy.Assault.Mech.zip)

**Comment by tsunamayo** [comment]
Okay it was in fact linked to children entity not your build in particular - it is now fixed. Awesome mech by the way @chunkblaster ! Cheers
